### ISSUE TITLE
中文帮助文件版本号没有更新

### ISSUE THREAD

**Issue by lychichem** [sparanoid/7z#10]
![default](https://cloud.githubusercontent.com/assets/9316590/11318636/e1ceb5e6-9095-11e5-8411-e581ab111079.PNG)

**Comment by sparanoid** [comment]
@lychichem 抱歉，这个 CHM 已经很长时间没有维护了，最近精力有限，我找时间看下，如果你感兴趣并且愿意帮助，非常欢迎
