### ISSUE TITLE
7z的图标没打算优化吗？

### ISSUE THREAD

**Issue by redguardofchina** [sparanoid/7z#30]
现在电脑分辨率很高，7z还在使用98时代的icon，就没打算优化吗？
7z很完美，唯独zip图标让很多人不想安装，真心想换成你们exe的图标

**Comment by xishizhe** [comment]
同感，图标不太美观，而且设置了7z为默认的解压缩软件后，所有的压缩文件都变丑了（分辨率变低），看着很不舒服。
