### ISSUE TITLE
在“开发者常见问题解答”中的错误

### ISSUE THREAD

**Issue by zhouxuanyi-zxy** [sparanoid/7z#40]
## 错误的翻译

_想要编译远吗您需要 Visual C++ 6.0 或更高版本。部分文件还需要来自 microsoft.com 的 Platform SDK。_

## 应翻译为

_想要编译源码您需要 Visual C++ 6.0 或更高版本。部分文件还需要来自 microsoft.com 的 Platform SDK。_

## 更多信息

_在 https://sparanoid.com/lab/7z/faq.html#developer_faq 页面_

**Comment by xiaopangju** [comment]
我建议这样改：
想要编译源码吗？您需要 Visual C++ 6.0 或更高版本。部分文件还需要来自 microsoft.com 的 Platform SDK。

Yours faithfully,

Haoran Du


________________________________
From: zhouxuanyi-zxy ***@***.***>
Sent: Tuesday, July 27, 2021 11:11:08 PM
To: sparanoid/7z ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sparanoid/7z] 在“开发者常见问题解答”中的错误 (#40)


错误的翻译

想要编译远吗您需要 Visual C++ 6.0 或更高版本。部分文件还需要来自 microsoft.com 的 Platform SDK。

应翻译为

想要编译源码您需要 Visual C++ 6.0 或更高版本。部分文件还需要来自 microsoft.com 的 Platform SDK。

更多信息

在 https://sparanoid.com/lab/7z/faq.html#developer_faq 页面

―

**Comment by xiaopangju** [comment]
@sparanoid could you please close this? The translation is correct now.
