### ISSUE TITLE
解压了以后能自动打开解压文件夹就好了

### ISSUE THREAD

**Issue by lovr377** [sparanoid/7z#47]
这里是 7-Zip 中文本地化仓库，只负责处理和翻译有关的问题，其它问题例如建议、bug 将不会在这里被接受。

## 错误的翻译

_请在这里输入翻译错误的字串_

## 应翻译为

_请在这里输入正确的翻译_

## 更多信息

_请在这里输入补充信息，如果并不是翻译错误，例如中文版的特定错误，也请在这里提供信息_

**Comment by xiaopangju** [comment]
这里是 7-Zip 中文本地化仓库，只负责处理和翻译有关的问题，其它问题例如建议、bug 将不会在这里被接受。

Yours faithfully,
Haoran Du
________________________________
From: lovr377 ***@***.***>
Sent: Saturday, December 4, 2021 6:34:54 PM
To: sparanoid/7z ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sparanoid/7z] 解压了以后能自动打开解压文件夹就好了 (Issue #47)


这里是 7-Zip 中文本地化仓库，只负责处理和翻译有关的问题，其它问题例如建议、bug 将不会在这里被接受。

错误的翻译

请在这里输入翻译错误的字串

应翻译为

请在这里输入正确的翻译

更多信息

请在这里输入补充信息，如果并不是翻译错误，例如中文版的特定错误，也请在这里提供信息

―
