### ISSUE TITLE
英语太差，能否代为提交功能建议？

### ISSUE THREAD

**Issue by renyouguo** [sparanoid/7z#5]
我知道这里不是提建议的地方，但我的英语水平不足以描述清楚功能需求，只得冒昧，如有打扰，还请见谅。

其实我要的就是Bandizip的功能：智能解压。
就是如果压缩包内有多个文件/文件夹，则自动解压到与压缩包同名的文件夹内；
如果压缩包内是单个文件或单文件夹，则直接解压显示内容。

这确实是多年使用压缩软件的一个痛点，谢谢。

**Comment by sparanoid** [comment]
目前比较忙，暂时没有精力去提交，希望理解
