### ISSUE TITLE
7z默认显示的文件大小，是字节为单位，能不能是智能显示文件大小，比如：KB、MB、GB？

### ISSUE THREAD

**Issue by dajbd** [sparanoid/7z#8]
7z默认显示的文件大小，是字节为单位，能不能是智能文件大小，比如：KB、MB、GB？

有时候显示一个超大数字，单位是byte，岂不是反人类？

帮忙提交一下反馈咯！谢谢了~

**Comment by JoeXie** [comment]
does this issue fixed?

**Comment by RealHenryGX** [comment]
Actually this might be useful to most users.
It shouldn't be labeled as invalid :(
